### ISSUE TITLE
Síntesis de gestión de software

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/sintesis-MariaC232#2]
[Sintesis de Gestión de proyectos.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-MariaC232/files/7147284/Sintesis.de.Gestion.de.proyectos.pdf)

**Comment by EDITH-R** [comment]
Calificación:20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
